version: '3'
services:
  php:
    image: jguyomard/laravel-php:7.3
    volumes:
      - ./FOTH:/var/www/
      - $HOME/.composer/:$HOME/.composer/
  nginx:
    image: jguyomard/laravel-nginx:1.13
    volumes_from:
      - php
    ports:
      - 8080:80
