version: '2'

services:
  web:
    env_file: .env
    build:
      context: ./
      dockerfile: web.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - app
  app:
    env_file: .env
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./:/var/www
